### PR TITLE
Added WordCamp Nuremberg Wapuus

### PR DESCRIPTION
**Pull request by staude**

### CODE REVIEW

**Comment by tekapo** [comment]
Wow! Thank you, @staude for many Wapuus!

**Comment by tekapo** [comment]
@staude 
Sorry, I forgot to tell you we have changed the method to add new Wapuus.
Could you add you Wapuus information to 
https://github.com/jawordpressorg/wapuu-api/blob/master/wapuu.csv
and send us a pull request?

**Comment by staude** [comment]
@tekapo thanks for merging. I commited the infos to the csv but i forgot to send a pull request last night :-o

**Comment by tekapo** [comment]
Thank you, again!

**Pull request merged**
