### PR TITLE
Adding the WordCamp Philly 2015 Wapuu to the archive.

### PR DESCRIPTION
**Pull request by TheTracyL**
Hi. 

I love Wapuu. I created some for WordCamp Philadelphia.
I hope you will allow me to add them to the archive.

Thank you!

### CODE REVIEW

**Comment by shield-9** [comment]
Great!

But you had better to fix an accessibility issue:
- ``'s alt attribute should be the name of each wapuu.

**Comment by TheTracyL** [comment]
Sorry I missed that, I set all the the alt tags.

Thank you!

**Comment by tekapo** [comment]
Wow! Thank you, @TheTracyL !

**Comment by TheTracyL** [comment]
Thank you!

**Pull request merged**
