### PR TITLE
Adding Ottawa Wapuu

### PR DESCRIPTION
**Pull request by Idealien**
http://2016.ottawa.wordcamp.org/

### CODE REVIEW

**Comment by miya0001** [comment]
Please give us pull request to Wapuu API. 😄 
https://github.com/jawordpressorg/wapuu-api

**Comment by Idealien** [comment]
https://github.com/jawordpressorg/wapuu-api/pull/7

I'm assuming this pull request has to be accepted in order for the .png to exist for the API to pull in?

The PNG is currently accessible at https://github.com/Idealien/wapuu/blob/gh-pages/wapuu-archive/ottawa-wapuu.png

**Comment by Idealien** [comment]
API pull / merge completed.
This one needs to be as well to have the image src for display:
https://jawordpressorg.github.io/wapuu/wapuu-archive/ottawa-wapuu.png

**Comment by miya0001** [comment]
Thanks!

**Pull request merged**
