### PR TITLE
r2, the rtCamp Wapuu

### PR DESCRIPTION
**Pull request by ganeshkerkar**

### CODE REVIEW

**Comment by tekapo** [comment]
Sorry, but you pull request would cause conflicts. Would you fix it and try again please? @ganeshkerkar

**Comment by ganeshkerkar** [comment]
I've updated the PR to fix the conflicts. Thanks @tekapo

**Comment by tekapo** [comment]
Ummm, please don't change the indent of other lines. @ganeshkerkar

**Comment by ganeshkerkar** [comment]
Sorry that was auto formatted. Reverted :)

**Comment by tekapo** [comment]
Thank you, @ganeshkerkar !

**Pull request merged**
