### PR TITLE
Add "Wapuu der BER" from the WordCamp Berlin 2015

### PR DESCRIPTION
**Pull request by 2ndkauboy**
I hope the alternative file name is fine :)

### CODE REVIEW

**Comment by tekapo** [comment]
Thank you, @2ndkauboy !

**Comment by 2ndkauboy** [comment]
Thanks for merging @tekapo.

I just realised, that it is only 300x300 pixels. Should I file in another PR? I already have to correct size available.

**Comment by tekapo** [comment]
Of course! Please send the PR! @2ndkauboy

**Comment by 2ndkauboy** [comment]
Here you go: #66.

**Pull request merged**
